-- 0010_seed_edital.sql — árvore oficial (Anexo IV) + mapeamento das 60 questões (revisável).

insert into public.topics (discipline_id, name, parent_id, order_index, code)
select d.id, v.name, null, v.ord, v.code from (values
  ('Língua Portuguesa','Compreensão de textos',1,'LP-1'),
  ('Língua Portuguesa','Ortografia oficial',2,'LP-2'),
  ('Língua Portuguesa','Mecanismos de coesão textual',3,'LP-3'),
  ('Língua Portuguesa','Emprego das classes de palavras',4,'LP-4'),
  ('Língua Portuguesa','Concordância nominal e verbal',5,'LP-5'),
  ('Língua Portuguesa','Sinal indicativo de crase',6,'LP-6'),
  ('Língua Portuguesa','Sinais de pontuação',7,'LP-7'),
  ('Língua Portuguesa','Significação das palavras',8,'LP-8'),
  ('Matemática','Conjuntos numéricos',1,'MAT-1'),
  ('Matemática','Razão e proporção; porcentagem',2,'MAT-2'),
  ('Matemática','Funções',3,'MAT-3'),
  ('Matemática','Equações e sistemas lineares',4,'MAT-4'),
  ('Matemática','Análise combinatória',5,'MAT-5'),
  ('Matemática','Probabilidade',6,'MAT-6'),
  ('Matemática','Estatística',7,'MAT-7'),
  ('Matemática','Matemática financeira',8,'MAT-8'),
  ('Matemática','Geometria plana',9,'MAT-9'),
  ('Matemática','Geometria espacial',10,'MAT-10'),
  ('Conhecimentos Específicos','Medição e Metrologia',1,null),
  ('Conhecimentos Específicos','Instrumentação e Controle',2,null),
  ('Conhecimentos Específicos','Mecânica',3,null),
  ('Conhecimentos Específicos','Mecânica dos Fluidos',4,null),
  ('Conhecimentos Específicos','Térmica e Termodinâmica',5,null),
  ('Conhecimentos Específicos','Resistência dos Materiais',6,null),
  ('Conhecimentos Específicos','Equipamentos de Processo',7,null),
  ('Conhecimentos Específicos','Segurança, Meio Ambiente e Saúde',8,null),
  ('Conhecimentos Específicos','Química',9,null),
  ('Conhecimentos Específicos','Processos de Refino',10,null),
  ('Conhecimentos Específicos','Física e Eletromagnetismo',11,null)
) as v(dname,name,ord,code) join public.disciplines d on d.name=v.dname
on conflict (discipline_id, name) do nothing;

insert into public.topics (discipline_id, name, parent_id, order_index, code)
select d.id, v.name, p.id, v.ord, v.code from (values
  ('Noções de metrologia','Medição e Metrologia',1,'CE-1'),
  ('Definições e unidades de medição','Medição e Metrologia',7,'CE-7'),
  ('Sistema Internacional de Unidades','Medição e Metrologia',8,'CE-8'),
  ('Instrumentos de medição (pressão, nível, temperatura, vazão)','Medição e Metrologia',9,'CE-9'),
  ('Transmissão e transmissores','Instrumentação e Controle',2,'CE-2'),
  ('Controle de processos (malha aberta e fechada)','Instrumentação e Controle',3,'CE-3'),
  ('Elementos finais de controle','Instrumentação e Controle',4,'CE-4'),
  ('Instrumentação: tipos, terminologia e simbologia','Instrumentação e Controle',5,'CE-5'),
  ('Sistemas instrumentados de segurança','Instrumentação e Controle',6,'CE-6'),
  ('Mecânica geral: estática, cinemática e dinâmica','Mecânica',10,'CE-10'),
  ('Conservação da energia mecânica','Mecânica',11,'CE-11'),
  ('Mecânica dos fluidos: propriedades, hidrostática, escoamento e perda de carga','Mecânica dos Fluidos',12,'CE-12'),
  ('Transmissão de calor: condução, convecção e radiação','Térmica e Termodinâmica',13,'CE-13'),
  ('Máquinas térmicas','Térmica e Termodinâmica',14,'CE-14'),
  ('Termodinâmica básica','Térmica e Termodinâmica',16,'CE-16'),
  ('Resistência dos materiais: tensões, flexão e torção','Resistência dos Materiais',15,'CE-15'),
  ('Equipamentos de processo: bombas, compressores e permutadores','Equipamentos de Processo',17,'CE-17'),
  ('Segurança do trabalho, meio ambiente e saúde','Segurança, Meio Ambiente e Saúde',18,'CE-18'),
  ('Química geral: modelos atômicos e classificação periódica','Química',19,'CE-19'),
  ('Ligações químicas','Química',20,'CE-20'),
  ('Cálculo estequiométrico','Química',21,'CE-21'),
  ('Estudo dos gases','Química',22,'CE-22'),
  ('Reações de oxidação-redução','Química',23,'CE-23'),
  ('Química inorgânica: ácidos, bases, sais e óxidos','Química',24,'CE-24'),
  ('Química orgânica: hidrocarbonetos e polímeros','Química',25,'CE-25'),
  ('Unidades de concentração','Química',26,'CE-26'),
  ('Transformações químicas e equilíbrio','Química',27,'CE-27'),
  ('Termoquímica','Química',28,'CE-28'),
  ('Soluções aquosas','Química',29,'CE-29'),
  ('Dispersões','Química',30,'CE-30'),
  ('Natureza elétrica da matéria','Química',31,'CE-31'),
  ('Operações unitárias','Química',32,'CE-32'),
  ('Noções de processos de refino','Processos de Refino',33,'CE-33'),
  ('Eletrostática','Física e Eletromagnetismo',34,'CE-34'),
  ('Cargas elétricas em movimento','Física e Eletromagnetismo',35,'CE-35'),
  ('Eletromagnetismo','Física e Eletromagnetismo',36,'CE-36'),
  ('Radiações eletromagnéticas','Física e Eletromagnetismo',37,'CE-37'),
  ('Noções de eletricidade e eletrônica','Física e Eletromagnetismo',38,'CE-38')
) as v(name,pname,ord,code)
join public.disciplines d on d.name='Conhecimentos Específicos'
join public.topics p on p.discipline_id=d.id and p.name=v.pname
on conflict (discipline_id, name) do nothing;

update public.questions qq set topic_id=t.id from (values
  (1,'Compreensão de textos'),
  (2,'Compreensão de textos'),
  (3,'Mecanismos de coesão textual'),
  (4,'Emprego das classes de palavras'),
  (5,'Significação das palavras'),
  (6,'Mecanismos de coesão textual'),
  (7,'Mecanismos de coesão textual'),
  (8,'Sinal indicativo de crase'),
  (9,'Sinais de pontuação'),
  (10,'Concordância nominal e verbal'),
  (11,'Conjuntos numéricos'),
  (12,'Matemática financeira'),
  (13,'Estatística'),
  (14,'Funções'),
  (15,'Estatística'),
  (16,'Razão e proporção; porcentagem'),
  (17,'Razão e proporção; porcentagem'),
  (18,'Equações e sistemas lineares'),
  (19,'Geometria plana'),
  (20,'Equações e sistemas lineares'),
  (21,'Química geral: modelos atômicos e classificação periódica'),
  (22,'Ligações químicas'),
  (23,'Estudo dos gases'),
  (24,'Química inorgânica: ácidos, bases, sais e óxidos'),
  (25,'Química orgânica: hidrocarbonetos e polímeros'),
  (26,'Radiações eletromagnéticas'),
  (27,'Química orgânica: hidrocarbonetos e polímeros'),
  (28,'Mecânica geral: estática, cinemática e dinâmica'),
  (29,'Resistência dos materiais: tensões, flexão e torção'),
  (30,'Mecânica geral: estática, cinemática e dinâmica'),
  (31,'Mecânica geral: estática, cinemática e dinâmica'),
  (32,'Resistência dos materiais: tensões, flexão e torção'),
  (33,'Resistência dos materiais: tensões, flexão e torção'),
  (34,'Instrumentos de medição (pressão, nível, temperatura, vazão)'),
  (35,'Eletromagnetismo'),
  (36,'Sistemas instrumentados de segurança'),
  (37,'Transmissão e transmissores'),
  (38,'Noções de metrologia'),
  (39,'Instrumentos de medição (pressão, nível, temperatura, vazão)'),
  (40,'Mecânica dos fluidos: propriedades, hidrostática, escoamento e perda de carga'),
  (41,'Cálculo estequiométrico'),
  (42,'Reações de oxidação-redução'),
  (43,'Termoquímica'),
  (44,'Unidades de concentração'),
  (45,'Unidades de concentração'),
  (46,'Soluções aquosas'),
  (47,'Dispersões'),
  (48,'Transformações químicas e equilíbrio'),
  (49,'Instrumentação: tipos, terminologia e simbologia'),
  (50,'Transmissão de calor: condução, convecção e radiação'),
  (51,'Eletrostática'),
  (52,'Máquinas térmicas'),
  (53,'Termodinâmica básica'),
  (54,'Eletromagnetismo'),
  (55,'Eletrostática'),
  (56,'Mecânica dos fluidos: propriedades, hidrostática, escoamento e perda de carga'),
  (57,'Máquinas térmicas'),
  (58,'Instrumentos de medição (pressão, nível, temperatura, vazão)'),
  (59,'Controle de processos (malha aberta e fechada)'),
  (60,'Equipamentos de processo: bombas, compressores e permutadores')
) as mm(qn,tname) join public.topics t on t.name=mm.tname
where qq.exam_id=(select id from public.exams where slug='transpetro-2023-dutos-e-terminais') and qq.question_number=mm.qn;
